language: java

jdk:
  - oraclejdk8

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

script: cd backend && ./gradlew check

notifications:
  email:
    on_success: never
    on_failure: change
