spring:
  profiles.active: default

logging:
  file: hermes.log
  level:
    org.springframework: INFO

---

spring:
  profiles: default

logging:
  level:
    org.apache.catalina: WARN
    org.springframework.security: DEBUG
    org.springframework.boot.test: DEBUG
    org.springframework.test: DEBUG
    org.hibernate.validator: WARN
    org.glassfish.jersey: DEBUG
    eu.socialedge.hermes: DEBUG

server:
  port: 9999

---

spring:
    profiles: production

logging:
  level:
    eu.socialedge.hermes: ERROR
    org.glassfish.jersey: ERROR

server:
    port: 8080