spring:
  profiles.active: dev

logging:
  file: hermes-application.log
  level:
    org.springframework: INFO

---

spring:
  profiles: dev

  data.mongodb.port: 6666
logging:
  level:
    org.apache.catalina: WARN
    org.springframework.security: DEBUG
    org.springframework.boot.test: DEBUG
    org.springframework.test: DEBUG
    org.hibernate.validator: WARN
    eu.socialedge.hermes: DEBUG

ext:
  google-maps:
    api: AIzaSyCluVkO-_MfzcNku1aocMtQp8ua8oUSE0o
