spring:
  profiles.active: dev

logging:
  file: hermes-application.log
  level:
    org.springframework: INFO

mongeez.enabled: false
---

spring:
  profiles: dev

logging:
  level:
    org.apache.catalina: WARN
    org.springframework.security: DEBUG
    org.springframework.boot.test: DEBUG
    org.springframework.test: DEBUG
    org.hibernate.validator: WARN
    eu.socialedge.hermes: DEBUG

mongeez:
    enabled: true
    location: dev/mongeez.xml

ext:
  google-maps:
    api: AIzaSyCluVkO-_MfzcNku1aocMtQp8ua8oUSE0o
  restpack:
#    apiToken: O0Bet7ddVPDE5EUMP9s0zmLALUCZ09j5ZUxdEDCURRphtGIv
    apiToken: oEI4cwtaONtBWVmNvpWHTsOrzGhG1a1MTwZgn6LtGhYaGhQL

gen:
  templates:
    schedule: scheduleTemplate.html
