spring:
  profiles.active: dev

logging:
  file: hermes-application.log
  level:
    org.springframework: INFO

---

spring:
  profiles: dev

  data.mongodb.port: 6666
logging:
  level:
    org.apache.catalina: WARN
    org.springframework.security: DEBUG
    org.springframework.boot.test: DEBUG
    org.springframework.test: DEBUG
    org.hibernate.validator: WARN
    eu.socialedge.hermes: DEBUG

domain:
  agency:
    name: КП СМР "ЕЛЕКТРОАВТОТРАНС"
    lang: uk
    phone: +3805427007002
    timeZone: Europe/Kiev
    url: http://trolleybus.sumy.ua/

ext:
  google-maps:
    api: AIzaSyCluVkO-_MfzcNku1aocMtQp8ua8oUSE0o
